### ISSUE TITLE
show timer as part of icon in OSX menu bar

### ISSUE THREAD

**Issue by dfl** [tomighty/tomighty#113]
it would be nice to see the timer countdown at a glance without having to click on the icon to reveal it.
perhaps this could be a configuration option

**Comment by christianmagill** [comment]
I love this suggestion!

**Comment by christianmagill** [comment]
Here's an app that does this. I'd love to see this as part of Tomighty!

https://itunes.apple.com/us/app/countdown-simple-menubar-timer/id1018859486?mt=12

**Comment by thatguyintech** [comment]
This would be a great feature!

**Comment by rgov** [comment]
Looks like this is a feature now. Check Preferences -> General.
