### ISSUE TITLE
Tomighty menu bar icon is invisible on a mac that has dark theme enabled

### ISSUE THREAD

**Issue by chriszimmerman** [tomighty/tomighty#123]
Hi all. I love using Tomighty. Keep up the awesome work!

<img width="436" alt="screen shot 2017-12-08 at 9 11 35 pm" src="https://user-images.githubusercontent.com/483359/33791615-685ef526-dc5c-11e7-8425-197bc4e556c4.png">

Believe it or not, I have Tomighty started when I took this screenshot. It's difficult to see this.

If I click where the hidden icon is and start a timer, it becomes visible.

<img width="437" alt="screen shot 2017-12-08 at 9 12 19 pm" src="https://user-images.githubusercontent.com/483359/33791617-7fc9a13e-dc5c-11e7-97cc-fe74c262ebaa.png">

Please make an icon that's visible for the dark theme menu bar. Thank you for your time.

**Comment by rgov** [comment]
I use the dark theme on macOS 10.13.4 and I do not see the same issue as you.

**Comment by chriszimmerman** [comment]
Apologies for taking forever to get back to this. I was using an old version of Tomighty (1.0.1). I installed a newer version 1.2.1 and I no longer have the issue.

I'm closing this issue. Apologies for the inconvenience. Thanks for making an awesome product. :)
