### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by ccidral** [tomighty/tomighty#14]
Add support for plugins so that people can extend Tomighty.

**Comment by ccidral** [comment]
Will be available in the next release so that @helvalius can turn his achievement system into a plugin.

**Comment by dobermai** [comment]
Just for thoughtfood: Here is an Article how to do this with the JavaSE ServiceLoader appraoch (or Netbeans Lookup). I had great experiences with the Netbeans Lookup approach in the past:

http://java.sun.com/developer/technicalArticles/javase/extensible/index.html

**Comment by ccidral** [comment]
Nice material!  We can take some ideas from it.

**Comment by ccidral** [comment]
Basic plugin support is done (cf6dda48e33b629af2f1aeca62e8c5150d52ea75, 52d17ad8dae30af0a874f02e4093dc0d5046d2d1). Documentation should be available soon. Here is a hello world plugin sample: https://github.com/ccidral/tomighty-helloworld-plugin
