### ISSUE TITLE
Show rectangles after using zh_TW locale message files

### ISSUE THREAD

**Issue by haocheng** [tomighty/tomighty#40]
Hi, 

I tried to add message files for zh_TW locale.
However, after using zh_TW properties files, several places will show rectangles instead.
Please see the following screenshots for details:
https://picasaweb.google.com/haocheng.lee/Tomighty

Thank you!

**Comment by ccidral** [comment]
Hi @haocheng,

Thanks for the translation and for reporting this bug.  I will work on it as soon as possible.

**Comment by haocheng** [comment]
Hi @ccidral, 

Thank you for the quick reply.

Please let me know if you need any additional information :)

**Comment by ccidral** [comment]
After doing some experiments, I found out that this is a bug with TextLayout.draw().  The characters are rendered correctly with Graphics2D.drawString().

**Comment by haocheng** [comment]
Hi @ccidral,

Thank you for the fix :)

I will submit a pull request then.

**Comment by ccidral** [comment]
OK, I'm still trying to figure it out how to fix that, but you can submit the pull request anyway.

**Comment by ccidral** [comment]
Fix done, committed and available for download as version 0.7.1.  Please @haocheng test it and let me know whether the fix works so that I can close this issue.

**Comment by haocheng** [comment]
Hi @ccidral,

I have tested 0.7.1 and it works great!

Thank you :)

**Comment by ccidral** [comment]
Nice!
