### ISSUE TITLE
Bug in russian translation

### ISSUE THREAD

**Issue by ArtemZ** [tomighty/tomighty#42]
Hi,
I just installed tomighty and noticed that russian translation is broken. Many charachters not displaing as question marks.
Check out this screenshot: http://funkyimg.com/u2/884/310/Screenshot-12.png
Please, update russian translation or make possible to switch to english
P.S: I'm running Ubuntu Linux 10.10 x64, OpenJDK 6

**Comment by ccidral** [comment]
Ouch!  This nasty bug also happens with the Chinese translation.  Can you confirm whether this bug happens on Windows too?  I suspect it happens under Linux only.  Anyway, I will fix it in version 0.7.1 and release it until next Friday.

I will create another issue for arbitrary selection of language.

Thanks for reporting this bug.

**Comment by ArtemZ** [comment]
> Can you confirm whether this bug happens on Windows too?
> Sorry, I don't have windows on my pc

**Comment by ccidral** [comment]
No problem, I will check that out later.  Thanks.

**Comment by ccidral** [comment]
Just found out that this bug happens when Tomighty is built on Windows.  It's a matter of configuring Maven to read resource files in UTF-8.  I will fix that tomorrow and a bugfix release will probably come out this weekend.

**Comment by ccidral** [comment]
Hi @ArtemZ, the fix is committed and available for download as version 0.7.1.  Please test it and let me know if it works so that I can close this issue.

**Comment by ArtemZ** [comment]
Hi @ccidral,
It looks good now. However I mentioned one untranslated phrase in tomighty's configuration: Allows dragging the window around. It can be translated as "Разрешить перетаскивание окошка".

**Comment by ccidral** [comment]
Ok, I will add this message to the file.
