### ISSUE TITLE
No sound on linux

### ISSUE THREAD

**Issue by ArtemZ** [tomighty/tomighty#45]
Hello,
I hear no sound from tomighty, no ticking or anything else. I tried to use custom tracs, but there is still nothing. Surely, my sound system is OK either Java sound system seems to be OK (for example Jitsi SIP client works normally on my computer no matter if it configured to use JavaSound or PortAudio)

**Comment by ccidral** [comment]
That's a known bug, sometimes I can hear sounds on Linux (Ubuntu), but most of the time I can't.  I will try to fix that in version 0.8.

Please take a loot at issue #17, could you verify whether you see similar error messages?

**Comment by ArtemZ** [comment]
Hello,
Yeah, that's exactly the same issue, sorry for creating this double.

**Comment by ccidral** [comment]
No problem.
