### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by ziembla** [tomighty/tomighty#53]
Hello, thanks for quite handy simple tool! It has just what it needs...

I'd like to add a Polish translation and have a messages_pl_PL.properties file ready but don't know how to upload it without installing git...

Can I email it or should I just paste it here in an "issue"? I've created a branch and uploaded the file there in the downloads section, can you pull it from there?

Regards

**Comment by ccidral** [comment]
Sure, no problem, I will download from there.  Thanks for the translation work!

**Comment by ziembla** [comment]
> Thanks for the translation work!

My pleasure.

Regards
Wojtek
