### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by w2m14** [tomighty/tomighty#54]
# General

Default = افتراضي
Click.to.select.a.file = انقر لتحديد ملف
# Tray message

First.time.using.Tomighty? = هل تستخدم Tomighty لأول مرة؟
Click.on.the.tomato.icon.to.start.using.it = انقر فوق أيقونة حبة الطماطم للبدء في استخدامه
# Tray menu

Options = خيارات
About = حول
Close = إغلاق
# About

About.Tomighty = حول Tomighty
# Options

Save = حفظ
Cancel = إلغاء
# Options / Times

Times = الأوقات
Short.break = راحة قصيرة
Long.break = راحة طويلة
minutes = دقيقة
# Options / User interface

User.interface = واجهة المستخدم
Theme = السمة
Show.remaining.time.on.tray = عرض الوقت المتبقي بجوار الساعة
Auto.hide.window = إخفاء النافذة آلياً
Allows.dragging.the.window.around = السماح بسحب النافذة وتغيير مكانها
Brushed.metal = معدني مصقول
Gradient = متدرج
Shiny = لامع
Grainy = حُبيبي
# Options / Sounds

Sounds = الأصوات
Enable.wind.sound = تمكين صوت الريح
Enable.tic-tac = تمكين صوت البندول
Enable.ding.sound = تمكين صوت الجرس
# UI states

Start.pomodoro = بدء جلسة
New.pomodoro = جلسة جديدة
Interrupt = إيقاف
Pomodoro.interrupted = تم إيقاف الجلسة
Pomodoro.finished = انتهت الجلسة
Take.a.break = أخذ راحة
Short = قصيرة
Long = طويلة
Restart = إعادة تشغيل
Restart.pomodoro = بدء الجلسة مجدداً
Break.finished = انتهت الراحة
Break.interrupted = تم قطع الراحة
Restart.break = بدء الراحة مجدداً

**Comment by ccidral** [comment]
Hey thanks a lot for the translation.  I will merge it into the master branch tomorrow.

**Comment by ccidral** [comment]
Some questions about this translation:
- What is the country-specific locale id? (e.g. ar-SA for Saudi Arabia)
- Can this translation be used for any arab-speaking country?

**Comment by w2m14** [comment]
It is in modern standard Arabic, so it is applicable for any Arab speaking country.

But if putting a country id is must, let it be ar-eg.

**Comment by ccidral** [comment]
Thanks for the info.  I will make it country-independent.

By the way, I recommend you to sign up for the discussion list so that you can be informed about further needs of translation updates.

**Comment by w2m14** [comment]
Thank you ccidral
