### ISSUE TITLE
CPU time optimalization

### ISSUE THREAD

**Issue by Visgean** [tomighty/tomighty#55]
It seems to me that tomighty is eating CPU for no reason, it seems to me that the update function is called every second which is completely unnecessary (i have this impression from https://github.com/ccidral/tomighty/blob/master/src/main/java/org/tomighty/time/CountdownTimer.java#L37 ), the solution is simple: the update function should be called only every minute unless it is in active state (popup has been activated or time < 1m) because most of the time tomighty is in inactive state and it needs to change the time/icon in tray only once per minute. I would do this by myself but I do not have any experience with java...

Thank you for reading this.

**Comment by ccidral** [comment]
Can you tell me a bit about your system (hardware and OS)?  On my machine (Intel i7, Windows 7) Tomighty consumes practically zero CPU time.  When the time changes it should not consume any significant amount of CPU time.

**Comment by ccidral** [comment]
Also tell me how much it consumes and what JVM you are running.

**Comment by Visgean** [comment]
I am running Ubuntu Natty and Tomighty 0.7.1, 
visgean@rewitaqia:~$ java -version 
java version "1.6.0_22"
OpenJDK Runtime Environment (IcedTea6 1.10.4) (6b22-1.10.4-0ubuntu1~11.04.1)
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)
I have this processor http://ark.intel.com/products/42925/Intel-Pentium-Processor-T4500-%281M-Cache-2_30-GHz-800-MHz-FSB%29 it´s last Dual-Core according to this list http://en.wikipedia.org/wiki/List_of_Intel_Pentium_Dual-Core_microprocessors . Tomighty is eating constantly 1% of cpu time. But it does not matter my point still is that it´s useless to run the update function every second since any changes are only once per minute...
