### ISSUE TITLE
Tags for finished pomodoros.

### ISSUE THREAD

**Issue by jsynowiec** [tomighty/tomighty#59]
User should be able to set tags for finished pomodoros that would be stored in eg. sqlite/nosql database. There should also be a functionality to view statistics and graphs for those tags.
###### Possible graphs/statistics
- How many pomodoros were tagged with specific tag,
- Overall time per tag/Number of finished pomodoros,
- Amount of pomodoros per tag per time of the day.

**Comment by ccidral** [comment]
This feature is very similar to the one described by issue #5.

However, I'm considering to make both the tagging feature and the recording/storage feature two separate plugins.  This would allow others to make plugins that implement tagging or recording in different ways.  Someone might want to record statistics on a remote host, for instance.  What do you think of this?

**Comment by jsynowiec** [comment]
Similar, but #5 is more about naming tasks that user is working on, and this one is about keywords for them.

**Comment by ccidral** [comment]
It just does not mention the method used for naming pomodoros, which will be the assignment of multiple tags.

**Comment by ccidral** [comment]
Task recording will not be built in Tomighty's core code. This should be handled by some plugin. See issue #72.
