### ISSUE TITLE
Task list manager

### ISSUE THREAD

**Issue by ccidral** [tomighty/tomighty#6]
The task list manager should allow users to:
- Add/edit/delete tasks
- Mark pomodoros completed during the task
- Mark interruptions occurred during the task
- Mark task as done
- Mark task as cancelled
- Change task order
- Set/change task priority

**Comment by DunkelKolar** [comment]
Yes, I would like to see this feature in the next version.

**Comment by agileapricot** [comment]
I like how simple and clear this app is. There are other apps out there that do that sort of thing like Pomodairo (http://code.google.com/p/pomodairo/).

I would vote to keep it clean, light and simple.

**Comment by ccidral** [comment]
Sure, I'm struggling to keep it as simple and usable as possible.  The above list of features will probably change.  I still need to sit down and take the time to think through regarding UI design and usability.  You guys are welcome to help me on this job  :)

**Comment by ccidral** [comment]
Task managing will not be built in Tomighty's core code. This should be handled by some plugin. See issue #72.
