### ISSUE TITLE
Any particular reason there's no .app available at tomighty.org?

### ISSUE THREAD

**Issue by appel** [tomighty/tomighty#80]
First of all, wonderful app, thanks!

I bundled tomighty-0.7.1.jar into an .app with Jar Bundler so I can put it in the dock. Used the .icns icon I found at [gettyicons.com](http://www.gettyicons.com/free-icon/176/paradise-fruit-icon-set/free-tomato-icon-png/) so it looks just like the real thing. Works great in Mountain Lion. Let me know if you'd like a pull request (assuming you already got permission for the logo).

**Comment by appel** [comment]
Did I say something stupid? If so I apologize, probably got a little carried away by my enthusiasm. Thanks anyway for a great app.

**Comment by ccidral** [comment]
Absolutely not! Please forgive me for not replying your message, I read it some days ago and completely forgot to answer it (I've been off Github for a few weeks).

A .app file would be wonderful. I don't know Jar Bundler however. Does it integrate with Maven?

**Comment by appel** [comment]
Well, that's a relief :) No worries, thanks for getting back to me! Honestly, I have no idea (yet) what Maven is, I have literally zero experience with java. But if you like (and assuming you're rocking OS X) I could just share the .app with you through dropbox so you could run/test it yourself.

**Comment by jrgifford** [comment]
Looks like something can. - http://mojo.codehaus.org/osxappbundle-maven-plugin/

**Comment by ccidral** [comment]
Great, I will give it a look as soon as I can. Thanks!

**Comment by appel** [comment]
Sorry it took me this long to get back to you, life has a way of getting in the way ;)

Here's the link to the .app at Dropbox, should you still be interested.
https://www.dropbox.com/sh/xqloc1boh47iifr/mQeQXNJc_e

**Comment by mysteryDate** [comment]
The app is not working for me (OSX 10.8.4). Literally nothing happens when launching the application (besides the OS warning be that it is "an application downloaded from the internet. Are you sure you want to open it?")

**Comment by appel** [comment]
Sorry it took me this long to respond, had some problems with a botched OS X install which I only came around to fixing last night (don't ask).

I just tried running the .app on my fresh 10.8.5 install and - although it's by no means a smooth ride - it does work. It's possible that Dropbox is messing up the app, so I've uploaded it to box.net instead, perhaps that fixes the problem for you. https://app.box.com/files/0/f/0/1/f_10695758415

Let me know if it works.

Edit: Hm, Box.net seems to kill it too.

**Comment by appel** [comment]
Apparently it's a feature, not a bug:
http://www.yourkit.com/download/mountain_lion.html

In short, you have to temporarily disable Gatekeeper (http://en.wikipedia.org/wiki/Gatekeeper_(OS_X)) in order for it to run. Why Apple chooses to display an error message that implies the .app is damaged instead of just indicating it's locked for security reasons is beyond me.

Re-upped the app to Dropbox, this time packaged as .dmg, here:
https://www.dropbox.com/s/hkgcbhehwdy5iu1/tomighty.dmg

**Comment by mysteryDate** [comment]
I pulled from your dropbox and everything is working perfectly! Thanks.

**Comment by ccidral** [comment]
I know this issue refers to the Java version of Tomighty, but since Tomighty for Mac is already out I think it's okay to close this issue.  The native OSX version is available for download at Tomighty's website, and the git repository is here: https://github.com/ccidral/tomighty-osx
