### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by sakai-to** [tomighty/tomighty#82]
Hello,

I have made a Japanese translation file of Tomighty and placed it in my fork of your repository.
Could you merge it to your repository?

Thank you.

**Comment by ccidral** [comment]
Sure, I will merge it. Thanks for the translation.

**Comment by ccidral** [comment]
By the way, would you mind making a pull request for your translation file?

**Comment by sakai-to** [comment]
I've made a pull request for this issue just now.
Thanks.

**Comment by ccidral** [comment]
Thanks, I will merge it.

**Comment by ccidral** [comment]
Done.
