### ISSUE TITLE
Icon bar no longer responds to clicks (OSX 10.8.4)

### ISSUE THREAD

**Issue by mysteryDate** [tomighty/tomighty#91]
I've been using tomighty for months now, but after an OSX update, it no longer works. The tomato appears in my menu bar, but nothing happens (besides a brief gray square) when it is clicked on.

**Comment by ccidral** [comment]
Which version of Java are you running?

**Comment by mysteryDate** [comment]
I'm running 1.6.0_34, I also posted this problem on the google groups (sorry for the x-posting!) and it was solved by updating to Java version 7! Thanks so much for your support (not to mention your program).

**Comment by ccidral** [comment]
No problem :)
