### ISSUE TITLE
No status bar icon on Mavericks

### ISSUE THREAD

**Issue by morewings** [tomighty/tomighty#94]
Installed on Mac OS X Mavericks and don't see any status bar icon. See screenshot.
![screen shot 2013-10-29 at 12 46 51](https://f.cloud.github.com/assets/1158959/1427325/71fcc9d4-4087-11e3-838e-7fd8f491914a.png)

**Comment by ccidral** [comment]
Thanks for reporting.  I'm still trying to figure out how to fix that.  I'm perplexed about how it looks fine on Mountain Lion but on Mavericks the icons are all messed up.

**Comment by ccidral** [comment]
Fixed and released. Please download the new version at http://www.tomighty.org

**Comment by zoolib** [comment]
I've got scrambled icons in a different application -- what was going wrong in tomighty that you fixed (as the change doesn't appear to be committed yet)?

**Comment by ccidral** [comment]
@zoolib The source code for Tomighty for Mac is at another Github repository: https://github.com/ccidral/tomighty-osx

This is the commit that contains the fix: https://github.com/ccidral/tomighty-osx/commit/0f5a91211d4510bd46cc59a3f77d0639f7af3333

**Comment by zoolib** [comment]
Brilliant, thank you.
As it turns out my bug was completely different. I was not properly retaining the buffer holding the actual pixels, and on Mavericks we're drawing once per screen, so things might work fine on the first screen, but not on the remainder.
