### ISSUE TITLE
Can't generate installer

### ISSUE THREAD

**Issue by piotr-sobczyk** [tomighty/tomighty#99]
I thought it will be as easy as mvn clean package, but it wasn't :/.
1. It seems that `generate-project` and `compile` goals are no longer valid for nsis-maven-plugin. Respectively `generate-headerfile` and `make` should be now used instead (see: http://mojo.codehaus.org/nsis-maven-plugin/plugin-info.html)
2. I updated pom.xml to use the correct goals but for some reason they weren't executed by package (with no error message or anything) even though they are bound to package phase.
3. So I ran them manually:

`mvn nsis:generate-headerfile`
`mvn nsis:make`

The first invocation worked ok but the second failed with following error: `Can't open script "setup.nsi"`. Even though I'm running these commands from top level pomodoro directory (parent project) where the file "setup.nsi" is present.

Any idea how to generate installer? Am I really the only one who struggles with that?

**Comment by piotr-sobczyk** [comment]
Now I know that I should enable maven profiles to include generating executable and installer, so I should run build as:

`mvn -P Windows,Installer clean pacakge`

**Comment by ccidral** [comment]
Hi @piotr-sobczyk, I'm sorry for not replying to you in time. I could not find the time to work on Tomighty lately, and I'm afraid I can't tell when I will be able to work on it again.
